/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ncpwdcswheadpwyypamp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jcHdkY3N3aGVhZHB3eXlwYW1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgwODIwMjQsImV4cCI6MjA4MzY1ODAyNH0.l-jcIBQbEiJ5Wy3Npl4VhTjnOH-qTt61HP7MOHmgJGI"